openapi: "3.0.3"

info:
  title: "サンプル API"
  version: "1.0.0"
  contact:
    name: Developer Takyafumin
    email: dev@example.com

servers:
  - url: "http://swagger-api:8083"
    description: mockサーバ
  - url: "http://localhost:8083"
    description: 開発環境

paths:
  "/api/v1/tasks":
    get:
      description: タスク一覧
      operationId: TaskList
      parameters:
        - name: status
          in: query
          required: false
          schema:
            type: integer
          description: タスクステータス
      responses:
        "200":
          description: "正常終了"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/TaskList"

  "/api/v1/tasks/{$task_id}":
    get:
      description: タスク詳細
      operationId: TaskShow
      parameters:
        - $ref: "#/components/parameters/PathTaskId"
      responses:
        "200":
          description: "正常終了"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Task"
        "404":
          description: "異常終了：データなし"

components:
  parameters:
    PathTaskId:
      name: task_id
      in: path
      required: true
      schema:
        type: integer
      description: タスクID

  schemas:
    StatusEnum:
      description: ステータス
      enum:
        - ready
        - doing
        - done
        - close
      type: string

    TaskList:
      properties:
        status:
          type: integer
        errorMessage:
          type: string
        totalCount:
          type: integer
        currentPage:
          type: integer
        tasks: 
          type: array
          items:
            type: object
            properties:
              id:
                type: integer
                format: integer
              title:
                type: string
              status:
                type: string
                format: StatusEnum
              limitDate:
                type: string
                format: date

    Task:
      type: object
      properties:
        status:
          type: integer
        errorMessage:
          type: string
        task:
          type: object
          properties:
            id:
              type: integer
              format: integer
            title:
              type: string
            description:
              type: string
            status:
              type: string
            assigneeId:
              type: integer
            createDate:
              type: string
              format: date
            limitDate:
              type: string
              format: date
